trigger:
- main

pool:
  name: my-pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'Install Dependencies'
- script: npm run build --if-present
  displayName: 'Build Angular App'
- script: npm test
  displayName: 'Run Tests'
